# Generated by Django 6.1.1 on 2026-09-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(default='GGH Community Association', max_length=255)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('monthly_contribution_amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
            ],
        ),
    ]
