# Generated by Django 6.1.1 on 2026-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(default='GGH Community Association', max_length=200)),
                ('association_tagline', models.CharField(blank=True, default='', max_length=255)),
                ('association_email', models.EmailField(blank=True, max_length=254)),
                ('association_phone', models.CharField(blank=True, max_length=30)),
                ('association_address', models.TextField(blank=True)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='One-time registration / joining fee for new members.', max_digits=10)),
                ('default_monthly_contribution', models.DecimalField(decimal_places=2, default=0.0, help_text='Default monthly contribution amount used when auto-generating expected payments.', max_digits=10)),
                ('loan_interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate (%) applied to loans.', max_digits=5)),
                ('max_loan_multiplier', models.DecimalField(decimal_places=2, default=3.0, help_text='Maximum loan amount as a multiple of total contributions.', max_digits=5)),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed penalty charged for late monthly contributions.', max_digits=10)),
                ('january_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use default', max_digits=10, null=True)),
                ('february_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('march_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('april_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('may_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('june_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('july_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('august_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('september_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('october_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('november_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('december_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiscal_year_start_month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='Month the financial year begins (usually January).')),
                ('enable_late_penalty', models.BooleanField(default=False)),
                ('allow_partial_payments', models.BooleanField(default=True)),
                ('auto_generate_expected_on_member_create', models.BooleanField(default=False, help_text='Automatically create ExpectedPayments for all months when a new member is registered.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
