# Generated by Django 6.1.1 on 2026-09-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_delete_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False, help_text='Show at the top of the list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to GGH Community', help_text='Large heading displayed in the hero banner.', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Short tagline under the hero title.', max_length=400)),
                ('hero_background_color', models.CharField(default='#343a40', help_text='CSS color for the hero background (e.g. #343a40 or #1a6b3c).', max_length=20)),
                ('hero_text_color', models.CharField(default='#ffffff', max_length=20)),
                ('show_login_button', models.BooleanField(default=True)),
                ('login_button_label', models.CharField(default='Member Login', max_length=60)),
                ('show_about', models.BooleanField(default=True)),
                ('about_title', models.CharField(default='About Us', max_length=200)),
                ('about_body', models.TextField(blank=True, help_text='Rich text / paragraphs describing the association.')),
                ('show_announcements', models.BooleanField(default=True)),
                ('announcements_title', models.CharField(default='Latest Announcements', max_length=200)),
                ('show_contact', models.BooleanField(default=True)),
                ('contact_title', models.CharField(default='Contact Us', max_length=200)),
                ('contact_body', models.TextField(blank=True)),
                ('show_stats', models.BooleanField(default=True, help_text='Show member count / year counters on homepage.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
            },
        ),
    ]
