# Generated by Django 6.1.1 on 2026-09-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('members', '0002_member_husband_father_alive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income_contribution', 'Member Contribution'), ('income_registration', 'Registration Fee'), ('income_other', 'Other Income'), ('income_loan_repayment', 'Loan Repayment'), ('expense_withdrawal', 'Withdrawal/Expense'), ('expense_loan_disbursement', 'Loan Disbursement')], max_length=50),
        ),
    ]
