# Generated by Django 6.1.1 on 2026-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financialtransaction_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='category',
            field=models.CharField(default='General', help_text='e.g. Office Supplies, Maintenance, Event', max_length=100),
        ),
    ]
