"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os                       # ⭐ for STATIC_ROOT path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)+l(pzmw6dwg=5&7gwf6#gy_*ca-=8xw=1f1=7@r)e(qry7co%'

# ⭐ DEBUG must be False in production
DEBUG = False

# ⭐ Updated for PythonAnywhere username: abumuaaz
ALLOWED_HOSTS = [
    'abumuaaz.pythonanywhere.com',
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    # Local apps
    'core',
    'accounts',
    'members',
    'committee',
    'contributions',
    'finance',
    'loans',
    'reports',
    'audit',
    'documents',
    'property',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Addis_Ababa'    # ⭐ Ethiopia timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# ⭐ Where collectstatic will gather static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# ═══════════════════════════════════════════════════════════════
#   EMAIL CONFIGURATION (Django 6.1+ uses MAILERS)
# ═══════════════════════════════════════════════════════════════

# ── For DEVELOPMENT: prints emails to terminal instead of sending ──
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

DEFAULT_FROM_EMAIL = 'GGH Community <noreply@gghcommunity.org>'

# ── For PRODUCTION: real Gmail SMTP (uncomment when ready) ──
# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
#         'OPTIONS': {
#             'host': 'smtp.gmail.com',
#             'port': 587,
#             'use_tls': True,
#             'username': 'your-email@gmail.com',
#             'password': 'your-16-char-app-password',
#         },
#     },
# }
# DEFAULT_FROM_EMAIL = 'GGH Community <your-email@gmail.com>'


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_URL = '/auth/login/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.RoleBackend',
    'django.contrib.auth.backends.ModelBackend',
]


JAZZMIN_SETTINGS = {
    'site_title': 'GGH System Admin',
    'site_header': 'GGH System',
    'site_brand': 'GGH System',
    'welcome_sign': 'Welcome to the GGH System Administration',
    'search_model': ['accounts.User'],
    'show_sidebar': True,
    'navigation_expanded': True,
    'custom_css': None,
    'custom_js': None,
    'show_ui_builder': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar': 'navbar-white navbar-light',
    'theme': 'default',
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
}


# ═══════════════════════════════════════════════════════════════
#   PROJECT-SPECIFIC SETTINGS
# ═══════════════════════════════════════════════════════════════

ASSOCIATION_NAME = 'GGH Community Association'

# ⭐ Updated for PythonAnywhere: abumuaaz
SITE_URL = 'http://abumuaaz.pythonanywhere.com'