# Generated by Django 6.1.1 on 2026-09-27 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_number', models.CharField(blank=True, help_text='National ID / Member ID', max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_member', models.BooleanField(default=False, help_text='Is this person a registered community member?')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique property code e.g. PROP-001', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('loaned', 'Loaned Out'), ('damaged', 'Damaged'), ('maintenance', 'Under Maintenance'), ('lost', 'Lost')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property/images/')),
                ('location', models.CharField(blank=True, help_text='Where the item is stored', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='property.category')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_code', models.CharField(help_text='e.g. LOAN-001', max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('loan_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('partial', 'Partially Returned'), ('lost', 'Lost')], default='active', max_length=20)),
                ('purpose', models.TextField(blank=True, help_text='Why is it being borrowed?', null=True)),
                ('condition_on_loan', models.CharField(blank=True, max_length=200, null=True)),
                ('condition_on_return', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_loans_handled', to=settings.AUTH_USER_MODEL)),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='property.loaner')),
                ('property_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='property.property')),
            ],
            options={
                'ordering': ['-loan_date'],
            },
        ),
    ]
