# Generated by Django 6.1.1 on 2026-09-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='husband_father_alive',
            field=models.BooleanField(default=True, verbose_name="Is husband's father alive?"),
        ),
        migrations.AddField(
            model_name='member',
            name='husband_mother_alive',
            field=models.BooleanField(default=True, verbose_name="Is husband's mother alive?"),
        ),
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='wife_father_alive',
            field=models.BooleanField(default=True, verbose_name="Is wife's father alive?"),
        ),
        migrations.AddField(
            model_name='member',
            name='wife_mother_alive',
            field=models.BooleanField(default=True, verbose_name="Is wife's mother alive?"),
        ),
        migrations.CreateModel(
            name='MemberChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_family_members', to='members.member')),
            ],
        ),
    ]
