# Generated by Django 6.1.1 on 2026-09-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_husband_father_alive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='husband_father_alive',
            field=models.BooleanField(default=True, verbose_name="Member's Father Alive"),
        ),
        migrations.AlterField(
            model_name='member',
            name='husband_mother_alive',
            field=models.BooleanField(default=True, verbose_name="Member's Mother Alive"),
        ),
        migrations.AlterField(
            model_name='member',
            name='wife_father_alive',
            field=models.BooleanField(default=True, verbose_name="Spouse's Father Alive"),
        ),
        migrations.AlterField(
            model_name='member',
            name='wife_mother_alive',
            field=models.BooleanField(default=True, verbose_name="Spouse's Mother Alive"),
        ),
        migrations.CreateModel(
            name='MemberRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('residential_address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Registration Request',
                'verbose_name_plural': 'Member Registration Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
