# Generated by Django 6.1.1 on 2026-09-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_husband_father_alive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='children_details',
            field=models.TextField(blank=True, help_text='List each child as: Name | Date of Birth | Gender (one per line)'),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='father_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='mother_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_father_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_mother_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='spouse_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
